# -*- coding: utf-8 -*-
"""
ComfyUI-ToolBag
自定义工具节点包，包含图像合成等节点。
"""

from .image_composite_center import (
    NODE_CLASS_MAPPINGS as COMPOSITE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMPOSITE_DISPLAY_MAPPINGS,
)
from .prompt_combine_dynamic import (
    NODE_CLASS_MAPPINGS as PROMPT_COMBINE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_COMBINE_DISPLAY_MAPPINGS,
)
from .screen_region_capture import (
    NODE_CLASS_MAPPINGS as SCREEN_CAPTURE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCREEN_CAPTURE_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **COMPOSITE_MAPPINGS,
    **PROMPT_COMBINE_MAPPINGS,
    **SCREEN_CAPTURE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **COMPOSITE_DISPLAY_MAPPINGS,
    **PROMPT_COMBINE_DISPLAY_MAPPINGS,
    **SCREEN_CAPTURE_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
