# -*- coding: utf-8 -*-
"""
ComfyUI-ToolBag
自定义工具节点包，包含图像合成等节点。
"""

from .image_composite_center import (
    NODE_CLASS_MAPPINGS as COMPOSITE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMPOSITE_DISPLAY_MAPPINGS,
)
from .prompt_combine_dynamic import (
    NODE_CLASS_MAPPINGS as PROMPT_COMBINE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_COMBINE_DISPLAY_MAPPINGS,
)
from .screen_region_capture import (
    NODE_CLASS_MAPPINGS as SCREEN_CAPTURE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCREEN_CAPTURE_DISPLAY_MAPPINGS,
)
from .image_resize_pad import (
    NODE_CLASS_MAPPINGS as RESIZE_PAD_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESIZE_PAD_DISPLAY_MAPPINGS,
)
from .folder_image_loader import (
    NODE_CLASS_MAPPINGS as FOLDER_LOADER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FOLDER_LOADER_DISPLAY_MAPPINGS,
)
from .delay_node import (
    NODE_CLASS_MAPPINGS as DELAY_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DELAY_DISPLAY_MAPPINGS,
)
from .image_alpha_fill import (
    NODE_CLASS_MAPPINGS as ALPHA_FILL_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ALPHA_FILL_DISPLAY_MAPPINGS,
)
from . import modelscope_routes

NODE_CLASS_MAPPINGS = {
    **COMPOSITE_MAPPINGS,
    **PROMPT_COMBINE_MAPPINGS,
    **SCREEN_CAPTURE_MAPPINGS,
    **RESIZE_PAD_MAPPINGS,
    **FOLDER_LOADER_MAPPINGS,
    **DELAY_MAPPINGS,
    **ALPHA_FILL_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **COMPOSITE_DISPLAY_MAPPINGS,
    **PROMPT_COMBINE_DISPLAY_MAPPINGS,
    **SCREEN_CAPTURE_DISPLAY_MAPPINGS,
    **RESIZE_PAD_DISPLAY_MAPPINGS,
    **FOLDER_LOADER_DISPLAY_MAPPINGS,
    **DELAY_DISPLAY_MAPPINGS,
    **ALPHA_FILL_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
